{
 "title": "S3Highload",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total objects size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "size_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total objects in storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "objects_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(uploads_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(deletions_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deletions panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "deletions_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "deletions_success_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "deletions_failure_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "uploads_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "uploads_success_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "uploads_failure_total{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}